# Generated by Django 5.1.1 on 2024-10-17 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='meal_options',
        ),
        migrations.AddField(
            model_name='booking',
            name='meal_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.meal'),
        ),
        migrations.DeleteModel(
            name='MealOption',
        ),
    ]
