# Generated by Django 5.1.1 on 2024-11-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
